matrix:
  include:
    - name: Python 3.7
      os: linux
      dist: bionic
      language: python
      python: 3.7

      script:
        - python scripts/test-instructions.py 'https://www.duckdb.org' '<p class="ver-python">([^<]+)</p>' | bash 
        - python -c "import duckdb" 


    - name: Python 2.7
      os: linux
      dist: bionic
      language: python
      python: 2.7

      script:
        - python scripts/test-instructions.py 'https://www.duckdb.org' '<p class="ver-python">([^<]+)</p>' | bash 
        - python -c "import duckdb" 


    - name: R Devel
      os: linux
      dist: xenial
      language: r
      r: devel

      script:
        - python scripts/test-instructions.py 'https://www.duckdb.org' '<p class="ver-r">([^<]+)</p>' | R
        - R -e "library('duckdb')"


    - name: R Devel
      os: osx
      osx_image: xcode11.5
      language: r
      r: devel

      install:
        true

      script:
        - python scripts/test-instructions.py 'https://www.duckdb.org' '<p class="ver-r">([^<]+)</p>' | R
        - R -e "library('duckdb')"